Interhyp/metadata-service

- .goreleaser.yaml
- internal/repository/metadata/metadata.go
- internal/service/owners/owners.go
- test/acceptance/metadatamock/metadata.go
- test/acceptance/util_dtos_test.go
- test/resources/acceptance-expected/owner-create-duplicate.json
- test/resources/acceptance-expected/owner-create.json
- test/resources/acceptance-expected/owner-patch-conflict.json
- test/resources/acceptance-expected/owner-patch.json
- test/resources/acceptance-expected/owner-unchanged.json
- test/resources/acceptance-expected/owner-update-conflict.json
- test/resources/acceptance-expected/owner-update.json
- test/resources/acceptance-expected/owner.json
- test/resources/acceptance-expected/owners.json
This PR fixes the implementation of the original PR that missed tests and the actual copying of the data.
RELTEC-10000
> Add `promoters` field to owner metadata

- .github/workflows/go.yaml
- README.md
- correctly report code coverage to codecov (acceptance and contract tests should contribute)
> fix(ci): fix codecov, release kafka update

- .github/workflows/snyk.yaml
> fix(ci): try to get snyk working with dependabot

- api/v1/apimodel.go
- docs/openapi-v3-spec.json
- internal/service/services/services.go
> feat(#52): add a description field for services

- internal/service/services/services.go
- internal/service/services/services_test.go
> feat(#52): add length validation for service description

- internal/service/owners/owners.go
- internal/service/repositories/repositories.go
- internal/service/repositories/repositories_test.go
- internal/service/util/DuplicateHelper.go
> fix(groups): fix multiple groups handling and prevent duplicates

- acorns/service/ownersint.go
- internal/service/owners/owners.go
- internal/service/services/acorn.go
- internal/service/services/services.go
> fix(#78): resolve groups on promoters endpoint

- api/v1/apimodel.go
- docs/openapi-v3-spec.json
- internal/service/owners/owners.go
> feat(#89): create user can handle groups

- api/v1/apimodel.go
- docs/openapi-v3-spec.json
> feat(#94): Support definition of predefined webhooks

- web/controller/ownerctl/ownerctl.go
- web/controller/repositoryctl/repositoryctl.go
- web/controller/servicectl/servicectl.go
- web/util/responsehelper.go
> fix(logs): Stop warning on user errors

- .github/workflows/go.yaml
- go.mod
> feat(#112): upgrade to go version 1.20

- api-generator/postprocess.pl
- api/v1/apimodel.go
- docs/openapi-v3-spec.json
- internal/service/repositories/repositories.go
- test/acceptance/metadatamock/metadata.go
- test/acceptance/util_dtos_test.go
- test/acceptance/util_web_test.go
- test/resources/acceptance-expected/repository-create.json
- test/resources/acceptance-expected/repository-update-newowner.json
- test/resources/acceptance-expected/repository-update.json
> feat(RELTEC-11059): added configuration for conditional build config

- .github/workflows/go.yaml
- test/acceptance/util_dtos_test.go
> feat(RELTEC-11059): fix struct literal uses unkeyed fields

- internal/web/middleware/jwt/jwt.go
> RELTEC-11094: fix panic in jwt middleware caused by unparsable tokens

- .github/workflows/go.yaml
> use go in version 1.20 instead of fix patched version

- internal/web/server/acorn.go
- internal/web/server/server.go
> increase server and request timeouts

- internal/web/controller/webhookctl/webhookctl.go
> feat(RELTEC-11171): process webhook async

- internal/web/middleware/cancellogger.go
- internal/web/server/server.go
More context cancellation logging so we can hunt down this weird cancel bug on push.
> feat(RELTEC-11181): add context cancellation logging

- go.mod
- go.sum
- internal/repository/bitbucket/bbclient/bbclient.go
- internal/web/server/server.go
> fix apm setup

- api/v1/apimodel.go
- docs/openapi-v3-spec.json
- internal/service/cache/deepcopy.go
- internal/service/cache/deepcopy_test.go
- internal/service/cache/ownercache.go
- internal/service/cache/repositorycache.go
- internal/service/cache/servicecache.go
- internal/service/mapper/owner.go
- internal/service/mapper/repository.go
- internal/service/repositories/repositories.go
- internal/service/repositories/repositories_test.go
> add support for watchers in repo config, simplify deepcopy

- internal/service/repositories/repositories.go
- internal/service/repositories/repositories_test.go
> fix assignments after expanding approvers and watchers

- api/v1/apimodel.go
- docs/openapi-v3-spec.json
- internal/service/services/services.go
- test/acceptance/util_dtos_test.go
- test/resources/acceptance-expected/service-create-crossref.json
- test/resources/acceptance-expected/service-create.json
- test/resources/acceptance-expected/service-patch-crossref-ownerchange.json
- test/resources/acceptance-expected/service-patch-crossref.json
- test/resources/acceptance-expected/service-patch-newowner.json
- test/resources/acceptance-expected/service-patch.json
- test/resources/acceptance-expected/service-update-newowner.json
- test/resources/acceptance-expected/service-update.json
> RELTEC-11243: add new attribute to service (internetExposed)

- .github/workflows/api-spec.yaml
- Dockerfile
Fixes for the previous merge (changes spec file location)
> fix(#172): fix spec file path

- internal/repository/metadata/metadata.go
> RELTEC-11165: add committer

- api/generated_apimodel.go
- api/openapi-v3-spec.json
- internal/service/owners/owners.go
- test/acceptance/util_dtos_test.go
- test/mock/metadatamock/metadata.go
- test/resources/acceptance-expected/owner-create-duplicate.json
- test/resources/acceptance-expected/owner-create.json
- test/resources/acceptance-expected/owner-notfound-deleteme.json
- test/resources/acceptance-expected/owner-notfound-migration-excellence.json
- test/resources/acceptance-expected/owner-notfound.json
- test/resources/acceptance-expected/owner-patch-conflict.json
- test/resources/acceptance-expected/owner-patch.json
- test/resources/acceptance-expected/owner-unchanged.json
- test/resources/acceptance-expected/owner-update-conflict.json
- test/resources/acceptance-expected/owner-update.json
- test/resources/acceptance-expected/owner.json
- test/resources/acceptance-expected/owners.json
> #200 add new owner attribute teams channel url

- internal/service/services/services.go
- internal/service/services/services_test.go
Fix error message...
Fixes #214
> fix(#214): fix error message

- api/generated_apimodel.go
- api/openapi-v3-spec.json
- internal/service/repositories/repositories.go
- internal/service/repositories/repositories_test.go
> add support for labels to repositories

- api/generated_apimodel.go
- api/openapi-v3-spec.json
- internal/service/owners/owners.go
- internal/service/owners/owners_test.go
> add support for owner links

- api/openapi-v3-spec.json
> fix Quicklink and Link examples in openapi-v3-spec.json

- go.mod
- go.sum
Items should now get pruned from redis cache correctly.
Fixes #248
> fix(#248): fix cache pruning

- api/openapi-v3-spec.json
> fix(RELTEC-11165): added new enum value

- api/openapi-v3-spec.json
- internal/web/controller/webhookctl/webhookctl.go
- test/acceptance/util_setup_test.go
- test/acceptance/webhook_acc_test.go
- test/mock/bitbucketmock/bitbucketmock.go
- test/resources/acceptance-expected/webhook-invalid.json
- test/resources/valid-config.yaml
Add missing test coverage for bitbucket webhook for PR validation
Fixes #292
> fix(#292): add tests

- internal/repository/bitbucket/repository.go
Bug fix (forgot to commit the fix)
Fixes #292
> fix(#292): fix build status call

- api/generated_apimodel.go
- api/openapi-v3-spec.json
- test/mock/metadatamock/metadata.go
- test/resources/acceptance-expected/repositories-filtered-service.json
- test/resources/acceptance-expected/repositories.json
- test/resources/acceptance-expected/repository.json
> RELTEC-11852: added "mergeConfig" as optional configuration

- api/generated_apimodel.go
- api/openapi-v3-spec.json
> RELTEC-11850: added "requireApprovals" as optional configuration

- README.md
> chore(#305): fix readme

- internal/service/updater/metadata.go
- internal/service/updater/owners.go
- internal/service/updater/repositories.go
- internal/service/updater/services.go
> fix(#275): error handling for context timeout

- api/generated_model_protected_ref.go
- api/openapi-v3-spec.yaml
- internal/service/repositories/repositories.go
- test/resources/acceptance-expected/repositories.json
- test/resources/acceptance-expected/repository-expanded-groups.json
> RELTEC-12108: added unexpanded copy of teams for exemptios

- api/openapi-v3-spec.yaml
- internal/repository/config/accessor_test.go
- internal/repository/config/accessors.go
- internal/repository/config/plumbing.go
- internal/service/mapper/owner.go
- internal/service/mapper/repository.go
- internal/service/vcswebhookshandler/vcswebhookshandler.go
> RELTEC-12262: small improvements

- api/generated_model_repository_configuration_dto.go
- api/generated_model_repository_configuration_patch_dto.go
- api/openapi-v3-spec.yaml
- internal/service/repositories/repositories.go
- internal/service/repositories/repositories_test.go
> RELTEC-12275: add new config property actionsAccess

- internal/service/repositories/repositories.go
> RELTEC-12278: support repository github ssh urls

- api/generated_model_repository_configuration_patch_dto.go
- api/openapi-v3-spec.yaml
- internal/service/repositories/repositories.go
- test/acceptance/repositoryctl_acc_test.go
- test/acceptance/util_dtos_test.go
- test/resources/acceptance-expected/repository-patch.json
Patch repository now patches all fields.
> feat(repository): patch now patches all fields

- .github/workflows/go.yaml
> RELTEC-12316: add required labels to docker image

- .github/dependabot.yaml
> RELTEC-11165-config-branch-name-separator

- internal/service/vcswebhookshandler/vcswebhookshandler.go
- internal/web/app/app.go
> RELTEC-12350: verify url of repository in changed yaml files

- go.mod
> feat(RELTEC-12350): verify url of repository in changed yaml files

- api/generated_model_owner_create_dto.go
- api/generated_model_owner_dto.go
- api/generated_model_owner_patch_dto.go
- api/openapi-v3-spec.yaml
- internal/service/owners/owners.go
> add field members to owner

- api/openapi-v3-spec.yaml
> feat(RELTEC-11165): fix schema and used enum values

- internal/service/mapper/owner.go
> RELTEC-12197: fix user not found should not result in a returning error

- .github/workflows/semantic-commit-message-check.yaml
> blubber test

- api/generated_model_condition_reference_dto.go
- api/openapi-v3-spec.yaml
> RELTEC-12457: add field for source of requireConditions

- api/generated_model_condition_reference_dto.go
- api/generated_model_repository_configuration_dto.go
- api/generated_model_repository_configuration_patch_dto.go
- api/openapi-v3-spec.yaml
- internal/service/repositories/repositories.go
> feat(RELTEC-12538): add enforcement to condition

- api-generator/generate.sh
- api/generated_model_repository_configuration_dto.go
- api/generated_model_repository_configuration_patch_dto.go
- api/openapi-v3-spec.yaml
- go.mod
- internal/service/repositories/repositories.go
- internal/service/repositories/repositories_test.go
> feat(RELTEC-11165): added new option for  deleteBranchOnMerge
